timeout: 1800s
options:
  logging: GCS_ONLY


substitutions:
  _REGION: asia-south1
  _SERVICE: air5star-ecommerce
  _REPO: air5star

steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID
      - .

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID

  - name: gcr.io/cloud-builders/gcloud
    id: Deploy to Cloud Run
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID \
          --region ${_REGION} \
          --allow-unauthenticated \
          --min-instances 1 \
          --port 3000 \
          --cpu 1 \
          --memory 1Gi \
          --add-cloudsql-instances air5star-ecommerce:asia-south1:air5star-postgres \
          --env-vars-file .cloudrun.env

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID