import { AProducts, SProducts, TProduct } from './types/product';

export const products: TProduct[] = [
  {
    id: '1',
    name: 'Ventilation',
    imageUrl: '/ventilation-img.webp',
    category: 'ventilation',
  },
  {
    id: '2',
    name: 'Air Conditioners',
    imageUrl: '/ac-1.webp',
    category: 'air-conditioning',
  },
];


// export const electronicProducts: AProducts[] = [
//   {
//     id: '1',
//     category: 'Air-conditioner',
//     product_title:
//       'Voltas SmartAir Inverter AC, 1.5 Ton, 3 star - 183V Vertis Smart Elite Gold With IoT',
//     description:
//       'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone. Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
//     brand: 'VOLTAS',
//     mrp: 70390,
//     price: 37390,
//     gross_volume: '1.5 Ton',
//     energy_rating: '3 Star',
//     swing: '4-way',
//     qty: 10,
//     imageUrl: '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac.jpg',
//     thumbnail_images: {
//       thumbnail1:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail1.jpg',
//       thumbnail2:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail2.jpg',
//       thumbnail3:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail3.jpg',
//       thumbnail4:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '2',
//     category: 'Air-conditioner',
//     product_title:
//       'Voltas SmartAir Inverter AC, 1 Ton, 3 star - 123V Vertis Smart Elite Gold With IoT',
//     description:
//       'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone. Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
//     brand: 'VOLTAS',
//     mrp: 60390,
//     price: 34390,
//     gross_volume: '1 Ton',
//     energy_rating: '3 Star',
//     swing: '4-way',
//     qty: 10,
//     imageUrl: '/voltas-ac/1ton-3star/voltas-1ton-3star-ac.jpg',
//     thumbnail_images: {
//       thumbnail1: '/voltas-ac/1ton-3star/voltas-1ton-3star-ac-thumbnail1.jpg',
//       thumbnail2: '/voltas-ac/1ton-3star/voltas-1ton-3star-ac-thumbnail2.jpg',
//       thumbnail3: '/voltas-ac/1ton-3star/voltas-1ton-3star-ac-thumbnail3.jpg',
//       thumbnail4: '/voltas-ac/1ton-3star/voltas-1ton-3star-ac-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '3',
//     category: 'Air-conditioner',
//     product_title:
//       'Voltas SmartAir Inverter AC, 1.5 Ton, 5 star - 185V Vertis Emerald',
//     description:
//       'Discover the Voltas Smart Air Inverter AC with super silent operation and energy-saving Sleep Mode. With 5-stage adjustable modes, it delivers personalized comfort and cost-effectiveness. Choose Voltas for a smart cooling solution in your home!',
//     brand: 'VOLTAS',
//     mrp: 77390,
//     price: 42990,
//     gross_volume: '1.5 Ton',
//     energy_rating: '5 Star',
//     swing: '4-way',
//     qty: 10,
//     imageUrl: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star.jpg',
//     thumbnail_images: {
//       thumbnail1: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail1.jpg',
//       thumbnail2: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail2.jpg',
//       thumbnail3: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail3.jpg',
//       thumbnail4: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '4',
//     category: 'Air-conditioner',
//     product_title:
//       'Voltas SmartAir Inverter AC, 1.5 Ton, 5 star - 185V Vertis Smart Elite Gold With IoT',
//     description:
//       'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone.Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
//     brand: 'VOLTAS',
//     mrp: 79390,
//     price: 44990,
//     gross_volume: '1.5 Ton',
//     energy_rating: '5 Star',
//     swing: '4-way',
//     qty: 10,
//     imageUrl: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star.jpg',
//     thumbnail_images: {
//       thumbnail1: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail1.jpg',
//       thumbnail2: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail2.jpg',
//       thumbnail3: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail3.jpg',
//       thumbnail4: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '5',
//     category: 'Air-conditioner',
//     product_title:
//       'Voltas SmartAir Inverter AC, 1 Ton, 5 star - 123V Vertis Smart Elite Gold With IoT',
//     description:
//       'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone. Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
//     brand: 'VOLTAS',
//     mrp: 67390,
//     price: 47390,
//     gross_volume: '1 Ton',
//     energy_rating: '5 Star',
//     swing: '4-way',
//     qty: 10,
//     imageUrl: '/voltas-ac/1ton-5star/voltas-1ton-5star.jpg',
//     thumbnail_images: {
//       thumbnail1: '/voltas-ac/1ton-5star/voltas-1ton-5star-thumbnail1.jpg',
//       thumbnail2: '/voltas-ac/1ton-5star/voltas-1ton-5star-thumbnail2.jpg',
//       thumbnail3: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail3.jpg',
//       thumbnail4: '/voltas-ac/1.5ton-5star/voltas-1.5ton-5star-thumbnail3.jpg',
//     },
//   },
//   {
//     id: '6',
//     category: 'Air-conditioner',
//     product_title:
//       'Voltas Adjustable Inverter Split AC, 2 Ton, 5 star - 245V Vertis Plus',
//     description:
//       'The Voltas Adjustable Inverter AC, is equipped with a unique Adjustable Mode. This innovative feature adapts tonge according to temperature and occupancy, delivering comfort while effectively managing power consumption to reduce electricity costs. Experience comfort and savings with Voltas!',
//     brand: 'VOLTAS',
//     mrp: 93390,
//     price: 58390,
//     gross_volume: '2 Ton',
//     energy_rating: '5 Star',
//     swing: '4-way',
//     qty: 10,
//     imageUrl: '/voltas-ac/2ton-5star/voltas-2ton-5star.jpg',
//     thumbnail_images: {
//       thumbnail1: '/voltas-ac/2ton-5star/voltas-2ton-5star-thumbnail1.jpg',
//       thumbnail2: '/voltas-ac/2ton-5star/voltas-2ton-5star-thumbnail2.jpg',
//       thumbnail3: '/voltas-ac/2ton-5star/voltas-2ton-5star-thumbnail3.jpg',
//       thumbnail4: '/voltas-ac/2ton-5star/voltas-2ton-5star-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '7',
//     category: 'AIR COOLER',
//     product_title: 'Room Air Cooler Windoor 55',
//     description:
//       ' Persol cooler equipped with honeycomb cooling pads for enduring cooling performance. Featuring a touch panel interface for intuitive control, enjoy convenient access to cooling settings',
//     brand: 'VOLTAS',
//     mrp: 16390,
//     price: 12390,
//     gross_volume: '55 LITRE',
//     energy_rating: '',
//     swing: '',
//     qty: 10,
//     imageUrl: '',
//     thumbnail_images: {
//       thumbnail1:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail1.jpg',
//       thumbnail2:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail2.jpg',
//       thumbnail3:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail3.jpg',
//       thumbnail4:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '8',
//     category: 'AIR COOLER',
//     product_title: 'Room Air Cooler Dlite 36',
//     description:
//       'Persol cooler equipped with honeycomb cooling pads for enduring cooling performance. Featuring a touch panel interface for intuitive control, enjoy convenient access to cooling settings',
//     brand: 'VOLTAS',
//     mrp: 11390,
//     price: 9390,
//     gross_volume: '36 LITRE',
//     energy_rating: '',
//     swing: '',
//     qty: 10,
//     imageUrl: '',
//     thumbnail_images: {
//       thumbnail1:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail1.jpg',
//       thumbnail2:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail2.jpg',
//       thumbnail3:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail3.jpg',
//       thumbnail4:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '9',
//     category: 'AIR COOLER',
//     product_title: "Voltas Perso'l Air Cooler DELITE 26",
//     description:
//       'Perso l cooler equipped with honeycomb cooling pads for enduring cooling performance. Featuring a touch panel interface for intuitive control, enjoy convenient access to cooling settings',
//     brand: 'VOLTAS',
//     mrp: 6380,
//     price: 5430,
//     gross_volume: '26 LITRE',
//     energy_rating: '',
//     swing: '',
//     qty: 10,
//     imageUrl: '',
//     thumbnail_images: {
//       thumbnail1:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail1.jpg',
//       thumbnail2:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail2.jpg',
//       thumbnail3:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail3.jpg',
//       thumbnail4:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '10',
//     category: 'AIR COOLER',
//     product_title: 'Tower Air Cooler Slimm 45',
//     description:
//       'Product Color: White-Grey,  Honeycomb Pad for Long Lasting Cooling, Motor with Thermal Overload Protection, Ice Chamber,Works on Inverter.45 litre Tower Cooler with honeycomb cooling padS',
//     brand: 'VOLTAS',
//     mrp: 11630,
//     price: 10403,
//     gross_volume: '45 LITRE',
//     energy_rating: '',
//     swing: '',
//     qty: 10,
//     imageUrl: '',
//     thumbnail_images: {
//       thumbnail1:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail1.jpg',
//       thumbnail2:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail2.jpg',
//       thumbnail3:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail3.jpg',
//       thumbnail4:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail4.jpg',
//     },
//   },
//   {
//     id: '11',
//     category: 'AIR COOLER',
//     product_title: 'Tower Air Cooler Slimm 55',
//     description:
//       'Product Color: White-Grey,  Honeycomb Pad for Long Lasting Cooling, Motor with Thermal Overload Protection, Ice Chamber,Works on Inverter. 55 litre Tower Cooler with honeycomb cooling padS',
//     brand: 'VOLTAS',
//     mrp: 12630,
//     price: 11568,
//     gross_volume: '55 LITRE',
//     energy_rating: '',
//     swing: '',
//     qty: 10,
//     imageUrl: '',
//     thumbnail_images: {
//       thumbnail1:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail1.jpg',
//       thumbnail2:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail2.jpg',
//       thumbnail3:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail3.jpg',
//       thumbnail4:
//         '/voltas-ac/1.5ton-3star/voltas-1.5ton-3star-ac-thumbnail4.jpg',
//     },
//   },



export const productsData = [
  {
    id: 'air-conditioning',
    category: 'air-conditioning',
    name: 'Air Conditioning',
    products: [
      {
        id: 1,
        category: 'air-conditioning',
        subCategory: 'SmartAir Inverter AC',
        brand: 'Voltas',
        productTitle:
          'Voltas SmartAir Inverter AC, 1.5 Ton, 3 star - 183V Vertis Smart Elite Gold With IoT',
        description:
          'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone. Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
        mrp: 70990,
        price: 37990,
        gst: 0.18,
        grossVolume: '1.5 Ton',
        energyRating: '3 Star',
        swing: '4-way',
        inverter_non_inverter: 'INVERTER',
        model: '183V Vertis Smart Elite Gold With IoT',
        imageUrl: '/ac/1-1.5ton-3star/main-img.jpg',
        thumbnail_images: {
          imageUrl: '/ac/1-1.5ton-3star/main-img.jpg',
          thumbnail1: '/ac/1-1.5ton-3star/tb-1.jpg',
          thumbnail2: '/ac/1-1.5ton-3star/tb-2.jpg',
          thumbnail3: '/ac/1-1.5ton-3star/tb-3.jpg',
          thumbnail4: '/ac/1-1.5ton-3star/tb-4.jpg',
        },
      },
      {
        id: 2,
        category: 'air-conditioning',
        subCategory: 'SmartAir Inverter AC',
        brand: 'Voltas',
        productTitle:
          'Voltas SmartAir Inverter AC, 1 Ton, 3 star - 123V Vertis Smart Elite Gold With IoT',
        description:
          'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone. Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
        mrp: 60990,
        price: 34990,
        gst: 0.18,
        grossVolume: '1 Ton',
        energyRating: '3 Star',
        swing: '4-way',
        inverter_non_inverter: 'INVERTER',
        model: '123V Vertis Smart Elite Gold With IoT',
        imageUrl: '/ac/2-1ton-3star/main-img.jpg',
        thumbnail_images: {
          imageUrl: '/ac/2-1ton-3star/main-img.jpg',
          thumbnail1: '/ac/2-1ton-3star/tb-1.jpg',
          thumbnail2: '/ac/2-1ton-3star/tb-2.jpg',
          thumbnail3: '/ac/2-1ton-3star/tb-3.jpg',
          thumbnail4: '/ac/2-1ton-3star/tb-4.jpg',
        },
      },
      {
        id: 3,
        category: 'air-conditioning',
        subCategory: 'SmartAir Inverter AC',
        brand: 'Voltas',
        productTitle:
          'Voltas SmartAir Inverter AC, 1.5 Ton, 5 star - 185V Vertis Emerald',
        description:
          'Discover the Voltas Smart Air Inverter AC with super silent operation and energy-saving Sleep Mode. With 5-stage adjustable modes, it delivers personalized comfort and cost-effectiveness. Choose Voltas for a smart cooling solution in your home!',
        mrp: 77990,
        price: 42990,
        gst: 0.18,
        grossVolume: '1.5 Ton',
        energyRating: '5 Star',
        swing: '4-way',
        inverter_non_inverter: 'INVERTER',
        model: '185V Vertis Emerald',
        imageUrl: '/ac/3-1.5ton-5star/main-img.jpg',
        thumbnail_images: {
          imageUrl: '/ac/3-1.5ton-5star/main-img.jpg',
          thumbnail1: '/ac/3-1.5ton-5star/tb-1.jpg',
          thumbnail2: '/ac/3-1.5ton-5star/tb-2.jpg',
          thumbnail3: '/ac/3-1.5ton-5star/tb-3.jpg',
          thumbnail4: '/ac/3-1.5ton-5star/tb-4.jpg',
        },
      },
      {
        id: 4,
        category: 'air-conditioning',
        subCategory: 'SmartAir Inverter AC',
        brand: 'Voltas',
        productTitle:
          'Voltas SmartAir Inverter AC, 1.5 Ton, 5 star - 185V Vertis Smart Elite Gold With IoT',
        description:
          'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone.Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
        mrp: 79990,
        price: 44990,
        gst: 0.18,
        grossVolume: '1.5 Ton',
        energyRating: '5 Star',
        swing: '4-way',
        inverter_non_inverter: 'INVERTER',
        model: '185V Vertis Smart Elite Gold With IoT',
        imageUrl: '/ac/4-1.5ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/4-1.5ton-5star/main-img.png',
          thumbnail1: '/ac/4-1.5ton-5star/tb-1.png',
          thumbnail2: '/ac/4-1.5ton-5star/tb-2.png',
          thumbnail3: '/ac/4-1.5ton-5star/tb-3.png',
          thumbnail4: '/ac/4-1.5ton-5star/tb-4.png',
        },
      },
      {
        id: 5,
        category: 'air-conditioning',
        subCategory: 'SmartAir Inverter AC',
        brand: 'Voltas',
        productTitle:
          'Voltas SmartAir Inverter AC, 1 Ton, 5 star - 125V Vertis Smart Elite Gold With IoT',
        description:
          'Experience the Voltas Smart Air Inverter AC, featuring silent operation, Sleep Mode, and IoT connectivity via the Voltas Smart App for convenient control from your smartphone. Enjoy comfort and savings with this energy-efficient choice for any home. Choose Voltas for smart cooling solutions!',
        mrp: 67990,
        price: 37990,
        gst: 0.18,
        grossVolume: '1 Ton',
        energyRating: '5 Star',
        swing: '4-way',
        inverter_non_inverter: 'INVERTER',
        model: '125V Vertis Smart Elite Gold With IoT',
        imageUrl: '/ac/5-1ton-5star/main-img.jpg',
        thumbnail_images: {
          imageUrl: '/ac/5-1ton-5star/main-img.jpg',
          thumbnail1: '/ac/5-1ton-5star/tb-1.jpg',
          thumbnail2: '/ac/5-1ton-5star/tb-2.jpg',
        },
      },
      {
        id: 6,
        category: 'air-conditioning',
        subCategory: 'Adjustable Inverter Split AC',
        brand: 'Voltas',
        productTitle:
          'Voltas Adjustable Inverter Split AC, 2 Ton, 5 star - 245V Vectra Plus',
        description:
          'The Voltas Adjustable Inverter AC, is equipped with a unique Adjustable Mode. This innovative feature adapts tonnage according to temperature and occupancy, delivering comfort while effectively managing power consumption to reduce electricity costs. Experience comfort and savings with Voltas!',
        mrp: 93990,
        price: 58990,
        gst: 0.18,
        grossVolume: '2 TON',
        energyRating: '5 Star',
        swing: '4-way',
        inverter_non_inverter: 'INVERTER',
        model: '245V Vectra Plus',
        imageUrl: '/ac/6-2ton-5star/main-img.jpg',
        thumbnail_images: {
          imageUrl: '/ac/6-2ton-5star/main-img.jpg',
          thumbnail1: '/ac/6-2ton-5star/tb-1.jpg',
          thumbnail2: '/ac/6-2ton-5star/tb-2.jpg',
          thumbnail3: '/ac/6-2ton-5star/tb-3.jpg',
          thumbnail4: '/ac/6-2ton-5star/tb-4.jpg',
        },
      },
      {
        id: 7,
        category: 'air-conditioning',
        subCategory: 'Adjustable Inverter AC',
        brand: 'Voltas',
        productTitle:
          'Voltas Adjustable Inverter AC, 1.5 Ton, 5 star- 185V Vertis Elite',
        description:
          '1.5 Ton 5 Star Adjustable Inverter AC with Adjustable mode. Runs at 2 different cooling capacities for different cooling needs.',
        mrp: 49990,
        price: 36490,
        gst: 0.18,
        grossVolume: '1.5 Ton',
        energyRating: '5 Star',
        swing: '',
        inverter_non_inverter: 'Adjustable Inverter',
        model: '5 star- 185V Vertis Elite',
        imageUrl: '/ac/7-1.5ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/7-1.5ton-5star/main-img.png',
          thumbnail1: '/ac/7-1.5ton-5star/tb-1.png',
          thumbnail2: '/ac/7-1.5ton-5star/tb-2.png',
        },
      },
      {
        id: 8,
        category: 'air-conditioning',
        subCategory: 'Inverter Window AC',
        brand: 'Voltas',
        productTitle:
          'Voltas Inverter Window AC, 1.5 Ton, 5 star - 185V Vertis Elite-A',
        description:
          'Discover superior cooling with Voltas Inverter Window ACs. Designed for optimal performance and energy efficiency, our window AC units provide consistent cooling for comfort in any weather. With easy installation and user-friendly controls, Voltas Inverter Window ACs offer convenience and reliability. Explore our range today for a cool and comfortable summer.',
        mrp: 49990,
        price: 34990,
        gst: 0.18,
        grossVolume: '1.5 Ton',
        energyRating: '5 Star',
        swing: '',
        inverter_non_inverter: 'Inverter Window AC',
        model: '185V Vertis Elite-A',
        imageUrl: '/ac/8-1.5ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/8-1.5ton-5star/main-img.png',
          thumbnail1: '/ac/8-1.5ton-5star/tb-1.png',
          thumbnail2: '/ac/8-1.5ton-5star/tb-2.png',
        },
      },
      {
        id: 9,
        category: 'air-conditioning',
        subCategory: 'Fixed Speed Window AC',
        brand: 'Voltas',
        productTitle:
          'Voltas Fixed Speed Window AC, 1 Ton, 3 star - 123 Vectra Platina',
        description:
          'Keep cool and comfortable with Voltas Fixed Speed Window ACs. Enjoy reliable cooling and efficient performance for consistent comfort. With easy installation and user-friendly controls, our window ACs provide convenience and dependability. Explore our range today for a refreshing atmosphere.',
        mrp: 35990,
        price: 27990,
        gst: 0.18,
        grossVolume: '1 Ton',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'Fixed Speed Window AC',
        model: '3 star - 123 Vectra Platina',
        imageUrl: '/ac/9-1ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/9-1ton-3star/main-img.png',
          thumbnail1: '/ac/9-1ton-3star/tb-1.png',
          thumbnail2: '/ac/9-1ton-3star/tb-2.png',
          thumbnail3: '/ac/9-1ton-3star/tb-3.png',
        },
      },
      {
        id: 10,
        category: 'air-conditioning',
        subCategory: 'Fixed Speed Window AC',
        brand: 'Voltas',
        productTitle:
          'Voltas Fixed Speed Window AC,1.5 Ton,3 Star-183 Vectra Pearl: Instant Cooling',
        description:
          'Keep cool and comfortable with Voltas Fixed Speed Window ACs. Enjoy reliable cooling and efficient performance for consistent comfort. With easy installation and user-friendly controls, our window ACs provide convenience and dependability. Explore our range today for a refreshing atmosphere.',
        mrp: 30000,
        price: 22000,
        gst: 0.18,
        grossVolume: '1.5 Ton',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'Fixed Speed Window AC',
        model: ',3 Star-183 Vectra Pearl: Instant Cooling',
        imageUrl: '/ac/10-1.5ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/10-1.5ton-3star/main-img.png',
          thumbnail1: '/ac/10-1.5ton-3star/tb-1.png',
          thumbnail2: '/ac/10-1.5ton-3star/tb-2.png',
        },
      },
      {
        id: 11,
        category: 'air-conditioning',
        subCategory: 'Fixed Speed Window AC',
        brand: 'Voltas',
        productTitle:
          'Voltas Fixed Speed Window AC, 2 Ton, 2 star, Instant Cooling- 242 Vectra Plus',
        description:
          'Keep cool and comfortable with Voltas Fixed Speed Window ACs. Enjoy reliable cooling and efficient performance for consistent comfort. With easy installation and user-friendly controls, our window ACs provide convenience and dependability. Explore our range today for a refreshing atmosphere.',
        mrp: 47990,
        price: 36990,
        gst: 0.18,
        grossVolume: '2 TON',
        energyRating: '2 star',
        swing: '',
        inverter_non_inverter: '2 star, Instant Cooling- 242 Vectra Plus',
        model: '2 star, Instant Cooling- 242 Vectra Plus',
        imageUrl: '/ac/11-2ton-2star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/11-2ton-2star/main-img.png',
          thumbnail1: '/ac/11-2ton-2star/tb-1.png',
          thumbnail2: '/ac/11-2ton-2star/tb-2.png',
        },
      },
      {
        id: 12,
        category: 'air-conditioning',
        subCategory: 'SPECIAL EDITION D SERIES',
        brand: 'BLUE STAR',
        productTitle:
          'SPECIAL EDITION D SERIES | INVERTER AC | 1.5 TON | 5 STAR',
        description:
          "Set your room temperature from anywhere using your smartphone. Blue Star's Wi-Fi enabled Smart App allows you to set the desired temperature and control your AC, The powerful air throw of 50 ft. ensures comfortable and uniform cooling in every corner of your room. This Special Edition AC with 5.41 ISEER will enable more savings in terms of electricity consumed. More the number of hours the AC is run, lesser the electricity consumed and greater are your savings!",
        mrp: 80000,
        price: 53990,
        gst: 0.18,
        grossVolume: '1.5 TON',
        energyRating: '5 STAR',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'D SERIES',
        imageUrl: '/ac/12-1.5ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/12-1.5ton-5star/main-img.png',
          thumbnail1: '/ac/12-1.5ton-5star/tb-1.png',
          thumbnail2: '/ac/12-1.5ton-5star/tb-2.png',
          thumbnail3: '/ac/12-1.5ton-5star/tb-3.png',
          thumbnail4: '/ac/12-1.5ton-5star/tb-4.png',
        },
      },
      {
        id: 13,
        category: 'air-conditioning',
        subCategory: 'HEAVY DUTY',
        brand: 'BLUE STAR',
        productTitle: 'HEAVY DUTY INVERTER AC | D SERIES | 2 TON | 3 STAR',
        description:
          "The powerful air throw of 50 ft. ensures comfortable and uniform cooling in every corner of your room. Set your room temperature from anywhere using your smartphone.\nBlue Star's Wi-Fi enabled Smart App allows you to set the desired temperature and control your AC.",
        mrp: 78000,
        price: 57990,
        gst: 0.18,
        grossVolume: '2 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'INVERTER AC',
        model: 'HEAVY DUTY INVERTER AC',
        imageUrl: '/ac/13-2ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/13-2ton-3star/main-img.png',
          thumbnail1: '/ac/13-2ton-3star/tb-1.png',
          thumbnail2: '/ac/13-2ton-3star/tb-2.png',
          thumbnail3: '/ac/13-2ton-3star/tb-3.png',
          thumbnail4: '/ac/13-2ton-3star/tb-4.png',
        },
      },
      {
        id: 14,
        category: 'air-conditioning',
        subCategory: 'HEAVY DUTY',
        brand: 'BLUE STAR',
        productTitle: 'HEAVY DUTY INVERTER AC | D SERIES | 1.5 TON | 5 STAR',
        description:
          "The powerful air throw of 50 ft. ensures comfortable and uniform cooling in every corner of your room. Set your room temperature from anywhere using your smartphone.\nBlue Star's Wi-Fi enabled Smart App allows you to set the desired temperature and control your AC.",
        mrp: 79000,
        price: 52990,
        gst: 0.18,
        grossVolume: '1.5 TON',
        energyRating: '5 STAR',
        swing: '',
        inverter_non_inverter: 'INVERTER AC',
        model: 'D SERIES',
        imageUrl: '/ac/14-1.5ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/14-1.5ton-5star/main-img.png',
          thumbnail1: '/ac/14-1.5ton-5star/tb-1.png',
          thumbnail2: '/ac/14-1.5ton-5star/tb-2.png',
          thumbnail3: '/ac/14-1.5ton-5star/tb-3.png',
        },
      },
      {
        id: 15,
        category: 'air-conditioning',
        subCategory: 'HEAVY DUTY',
        brand: 'BLUE STAR',
        productTitle: 'HEAVY DUTY INVERTER AC | V SERIES | 1.7 TON | 3 STAR',
        description:
          "The powerful air throw of 50 ft. ensures comfortable and uniform cooling in every corner of your room. Set your room temperature from anywhere using your smartphone.\nBlue Star's Wi-Fi enabled Smart App allows you to set the desired temperature and control your AC.",
        mrp: 69000,
        price: 44990,
        gst: 0.18,
        grossVolume: '1.7TON',
        energyRating: '5 STAR',
        swing: '',
        inverter_non_inverter: 'INVERTER AC',
        model: 'V SERIES',
        imageUrl: '/ac/15-1.7ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/15-1.7ton-3star/main-img.png',
          thumbnail1: '/ac/15-1.7ton-3star/tb-1.png',
          thumbnail2: '/ac/15-1.7ton-3star/tb-2.png',
          thumbnail3: '/ac/15-1.7ton-3star/tb-3.png',
        },
      },
      {
        id: 16,
        category: 'air-conditioning',
        subCategory: 'HEAVY DUTY',
        brand: 'BLUE STAR',
        productTitle: 'HEAVY DUTY FIXED SPEED AC | A SERIES | 2.2 TON | 2 STAR',
        description:
          'The powerful air throw of 45 ft. ensures comfortable and uniform cooling in every corner of your room',
        mrp: 85000,
        price: 69990,
        gst: 0.18,
        grossVolume: '2.2 TON',
        energyRating: '2 STAR',
        swing: '',
        inverter_non_inverter: 'Inverter Split AC',
        model: 'A SERIES',
        imageUrl: '/ac/16-2.2ton-2star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/16-2.2ton-2star/main-img.png',
          thumbnail1: '/ac/16-2.2ton-2star/tb-1.png',
          thumbnail2: '/ac/16-2.2ton-2star/tb-2.png',
        },
      },
      {
        id: 17,
        category: 'air-conditioning',
        subCategory: 'HEAVY DUTY FIXED SPEED AC',
        brand: 'BLUE STAR',
        productTitle: 'HEAVY DUTY FIXED SPEED AC | D SERIES | 1.6 TON | 3 STAR',
        description:
          'his AC features a powerful compressor that provides superior cooling performance even at extreme temperatures up to 56\u00b0C. This AC comes with a 43 inch large IDU which ensures maximum cooling under extreme ambient conditions.',
        mrp: 63000,
        price: 49990,
        gst: 0.18,
        grossVolume: '1.6 TON',
        energyRating: '5 STAR',
        swing: '',
        inverter_non_inverter: 'INVERTER AC',
        model: 'D SERIES',
        imageUrl: '/ac/17-1.6ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/17-1.6ton-3star/main-img.png',
          thumbnail1: '/ac/17-1.6ton-3star/tb-1.png',
          thumbnail2: '/ac/17-1.6ton-3star/tb-2.png',
          thumbnail3: '/ac/17-1.6ton-3star/tb-3.png',
        },
      },
      {
        id: 18,
        category: 'air-conditioning',
        subCategory: 'HOT & COLD INVERTER AC',
        brand: 'BLUE STAR',
        productTitle:
          'HOT & COLD INVERTER AC | D SERIES -2\u00b0C to 52\u00b0C | 1 TON | 3 STAR',
        description:
          'This Hot & Cold AC cools in summer, warms in winter and keeps you comfortable throughout the year. The specially designed sensors in the outdoor unit detects freezing on the condenser coil. The temperature of the coil is then raised until the ice defrosts, ensuring that the AC provides\nuninterrupted hot air.',
        mrp: 55500,
        price: 36990,
        gst: 0.18,
        grossVolume: '1 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'INVERTER AC',
        model: 'D SERIES',
        imageUrl: '/ac/18-1ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/18-1ton-3star/main-img.png',
          thumbnail1: '/ac/18-1ton-3star/tb-1.png',
          thumbnail2: '/ac/18-1ton-3star/tb-1.png',
        },
      },
      {
        id: 19,
        category: 'air-conditioning',
        subCategory: 'WINDOW AC',
        brand: 'BLUE STAR',
        productTitle: 'FIXED SPEED WINDOW AC | L SERIES | 0.8 TON | 3 STAR',
        description:
          'Pre-set mode to instantly cool the room during extreme summers. The Eco Mode helps save on your electricity bills, while giving you a comfortable cooling experience.',
        mrp: 30000,
        price: 25490,
        gst: 0.18,
        grossVolume: '0.8 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'WINDOW AC',
        model: 'L SERIES',
        imageUrl: '/ac/19-0.8ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/19-0.8ton-3star/main-img.png',
          thumbnail1: '/ac/19-0.8ton-3star/tb-1.png',
          thumbnail2: '/ac/19-0.8ton-3star/tb-2.png',
        },
      },
      {
        id: 20,
        category: 'air-conditioning',
        subCategory: 'WINDOW AC',
        brand: 'BLUE STAR',
        productTitle: 'FIXED SPEED WINDOW AC | L SERIES | 1 TON | 3 STAR',
        description:
          'Pre-set mode to instantly cool the room during extreme summers. The Eco Mode helps save on your electricity bills, while giving you a comfortable cooling experience.',
        mrp: 33000,
        price: 26990,
        gst: 0.18,
        grossVolume: '1 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'WINDOW AC',
        model: 'L SERIES',
        imageUrl: '/ac/20-1ton-3star/main-img.png',
        thumbnail_images: {
          thumbnail1: '/ac/20-1ton-3star/tb-1.png',
          thumbnail2: '/ac/20-1ton-3star/tb-2.png',
        },
      },
      {
        id: 21,
        category: 'air-conditioning',
        subCategory: 'WINDOW AC',
        brand: 'BLUE STAR',
        productTitle: 'FIXED SPEED WINDOW AC | P SERIES | 1.5 TON | 3 STAR',
        description:
          'The AC is designed to deliver powerful cooling during extreme summers with minimum derating  Pre-set mode to instantly cool the room during extreme summers. The Eco Mode helps save on your electricity bills, while giving you a comfortable cooling experience.',
        mrp: 39500,
        price: 30490,
        gst: 0.18,
        grossVolume: '1.5 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'WINDOW AC',
        model: 'P SERIES',
        imageUrl: '/ac/21-1.5ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/21-1.5ton-3star/main-img.png',
          thumbnail1: '/ac/21-1.5ton-3star/tb-1.png',
          thumbnail2: '/ac/21-1.5ton-3star/tb-2.png',
        },
      },
      {
        id: 22,
        category: 'air-conditioning',
        subCategory: 'WINDOW AC',
        brand: 'BLUE STAR',
        productTitle: 'FIXED SPEED WINDOW AC | E SERIES | 2 TON | 3 STAR',
        description:
          'Pre-set mode to instantly cool the room during extreme summers. The AC remembers the last set mode and automatically resumes functioning with the same pre-set mode,  In the Dry Mode, the AC controls humidity by removing excess moisture from the indoor air. ensuring convenience after power cuts.',
        mrp: 40000,
        price: 37990,
        gst: 0.18,
        grossVolume: '2 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'WINDOW AC',
        model: 'E SERIES',
        imageUrl: '/ac/22-2ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/22-2ton-3star/main-img.png',
          thumbnail1: '/ac/22-2ton-3star/tb-1.png',
          thumbnail2: '/ac/22-2ton-3star/tb-2.png',
        },
      },
      {
        id: 23,
        category: 'air-conditioning',
        subCategory: 'Split AC',
        brand: 'DAIKIN',
        productTitle: '1.0 Ton 3 Star Inverter Split AC, FTKC35UV',
        description:
          'Now, you do not need to worry about air-conditioning operations at high ambient temperature. This model works upto 52 deg Celsius ambient temperature. Daikin Swing Inverter ACs has 7 Sensors located on IDU and ODU. Each of these sensors has role to play in the working of air-conditioning that improves overall performance, provide comfort to users and help to increase durability and life of the AC.',
        mrp: 47500,
        price: 34300,
        gst: 0.18,
        grossVolume: '1 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'FTKC35UV',
        imageUrl: '/ac/23-1ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/23-1ton-3star/main-img.png',
          thumbnail1: '/ac/23-1ton-3star/tb-1.png',
          thumbnail2: '/ac/23-1ton-3star/tb-2.png',
          thumbnail3: '/ac/23-1ton-3star/tb-3.png',
        },
      },
      {
        id: 24,
        category: 'air-conditioning',
        subCategory: 'Split AC',
        brand: 'DAIKIN',
        productTitle: '1.0 Ton 5 Star Inverter Split AC, Copper, JTKJ35U',
        description:
          'The intelligent eye operation detects human movement in a room. If no one is present in room for more than 20 minutes, the operation automatically changes to energy saving operation and save energy.',
        mrp: 60900,
        price: 42400,
        gst: 0.18,
        grossVolume: '1 TON',
        energyRating: '5 STAR',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'JTKJ35U',
        imageUrl: '/ac/24-1ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/24-1ton-5star/main-img.png',
          thumbnail1: '/ac/24-1ton-5star/tb-1.png',
          thumbnail2: '/ac/24-1ton-5star/tb-2.png',
          thumbnail3: '/ac/24-1ton-5star/tb-3.png',
        },
      },
      {
        id: 25,
        category: 'air-conditioning',
        subCategory: 'Split AC',
        brand: 'DAIKIN',
        productTitle: '1.5 Ton 3 Star Inverter Split AC, FTKC50UV',
        description:
          'Now, you do not need to worry about air-conditioning operations at high ambient temperature. This model works upto 52 deg Celsius ambient temperature. Daikin Swing Inverter ACs has 7 Sensors located on IDU and ODU. Each of these sensors has role to play in the working of air-conditioning  that improves overall performance, provide comfort to users and help to increase durability and life of the AC.',
        mrp: 58200,
        price: 37900,
        gst: 0.18,
        grossVolume: '1.5 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'FTKC50UV',
        imageUrl: '/ac/25-1.5ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/25-1.5ton-3star/main-img.png',
          thumbnail1: '/ac/25-1.5ton-3star/tb-1.png',
          thumbnail2: '/ac/25-1.5ton-3star/tb-2.png',
        },
      },
      {
        id: 26,
        category: 'air-conditioning',
        subCategory: 'Hot and Cold Inverter Split AC',
        brand: 'DAIKIN',
        productTitle:
          '1.5 Ton 5 Star Hot and Cold Inverter Split AC, Copper, FTXF50U',
        description:
          'Daikin Swing Inverter ACs has 7 Sensors located on IDU and ODU. Each of these sensors has role to play in the working of air-conditioning  that improves overall performance, provide Dew Clean Technology is a one button operation, that, when activated, automatically cleans the evaporator coil of the indoor unit heat exchanger by utilizing condensate water. This allows for better cleaning of Indoor Unit Heat Exchanger which ensures better airflow & consistent cooling performance throughout The 3 Stage Air Filtration process captures micro dust particles and eliminates pollutants & airborne pathogens such as viruses, bacteria, mould, and fungi to make the indoor air clean, safe, and fresh. comfort to users and help to increase durability and life of the AC.',
        mrp: 85000,
        price: 62200,
        gst: 0.18,
        grossVolume: '1.5 TON',
        energyRating: '5 STAR',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'FTXF50U',
        imageUrl: '/ac/26-1.5ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/26-1.5ton-5star/main-img.png',
          thumbnail1: '/ac/26-1.5ton-5star/tb-1.png',
          thumbnail2: '/ac/26-1.5ton-5star/tb-2.png',
          thumbnail3: '/ac/26-1.5ton-5star/tb-3.png',
        },
      },
      {
        id: 27,
        category: 'air-conditioning',
        subCategory: 'Split AC',
        brand: 'DAIKIN',
        productTitle: '1.8 Ton 5 Star Inverter Split AC, Copper, JTKJ60U',
        description:
          'Daikin Swing Inverter ACs has 7 Sensors located on IDU and ODU. Each of these sensors has role to play in the working of air-conditioning  that improves overall performance, provide Dew Clean Technology is a one button operation, that, when activated, automatically cleans the evaporator coil of the indoor unit heat exchanger by utilizing condensate water. This allows for better cleaning of Indoor Unit Heat Exchanger which ensures better airflow & consistent cooling performance throughout The 3 Stage Air Filtration process captures micro dust particles and eliminates pollutants & airborne pathogens such as viruses, bacteria, mould, and fungi to make the indoor air clean, safe, and fresh. comfort to users and help to increase durability and life of the AC.',
        mrp: 92200,
        price: 67700,
        gst: 0.18,
        grossVolume: '1.8 TON',
        energyRating: '5 STAR',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'JTKJ60U',
        imageUrl: '/ac/27-1.8ton-5star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/27-1.8ton-5star/main-img.png',
          thumbnail1: '/ac/27-1.8ton-5star/tb-1.png',
          thumbnail2: '/ac/27-1.8ton-5star/tb-2.png',
          thumbnail3: '/ac/27-1.8ton-5star/tb-3.png',
        },
      },
      {
        id: 28,
        category: 'air-conditioning',
        subCategory: 'Split AC',
        brand: 'DAIKIN',
        productTitle:
          '1.8 Ton 3 Star Hot and Cold Inverter Split AC, Copper, FTHT60U',
        description:
          'Daikin Swing Inverter ACs has 7 Sensors located on IDU and ODU. Each of these sensors has role to play in the working of air-conditioning  that improves overall performance, provide Dew Clean Technology is a one button operation, that, when activated, automatically cleans the evaporator coil of the indoor unit heat exchanger by utilizing condensate water. This allows for better cleaning of Indoor Unit Heat Exchanger which ensures better airflow & consistent cooling performance throughout The 3 Stage Air Filtration process captures micro dust particles and eliminates pollutants & airborne pathogens such as viruses, bacteria, mould, and fungi to make the indoor air clean, safe, and fresh. comfort to users and help to increase durability and life of the AC.',
        mrp: 76600,
        price: 56500,
        gst: 0.18,
        grossVolume: '1.8 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'FTHT60U',
        imageUrl: '/ac/28-1.8ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/28-1.8ton-3star/main-img.png',
          thumbnail1: '/ac/28-1.8ton-3star/tb-1.png',
          thumbnail2: '/ac/28-1.8ton-3star/tb-2.png',
          thumbnail3: '/ac/28-1.8ton-3star/tb-3.png',
        },
      },
      {
        id: 29,
        category: 'air-conditioning',
        subCategory: 'Split AC',
        brand: 'DAIKIN',
        productTitle: '2.02 Ton 3 Star Inverter Split AC, Copper, FTKL71U',
        description:
          'Daikin Swing Inverter ACs has 7 Sensors located on IDU and ODU. Each of these sensors has role to play in the working of air-conditioning  that improves overall performance, provide Dew Clean Technology is a one button operation, that, when activated, automatically cleans the evaporator coil of the indoor unit heat exchanger by utilizing condensate water. This allows for better cleaning of Indoor Unit Heat Exchanger which ensures better airflow & consistent cooling performance throughout The 3 Stage Air Filtration process captures micro dust particles and eliminates pollutants & airborne pathogens such as viruses, bacteria, mould, and fungi to make the indoor air clean, safe, and fresh. comfort to users and help to increase durability and life of the AC.',
        mrp: 64800,
        price: 64800,
        gst: 0.18,
        grossVolume: '2.02 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'INVERTER',
        model: 'FTKL71U',
        imageUrl: '/ac/29-2.02ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/29-2.02ton-3star/main-img.png',
          thumbnail1: '/ac/29-2.02ton-3star/tb-1.png',
          thumbnail2: '/ac/29-2.02ton-3star/tb-1.png',
          thumbnail3: '/ac/29-2.02ton-3star/tb-1.png',
        },
      },
      {
        id: 30,
        category: 'air-conditioning',
        subCategory: 'Split AC',
        brand: 'DAIKIN',
        productTitle: '0.8 Ton 3 Star Non Inverter Split AC, FTL30UV',
        description:
          'Econo mode enables efficient operation by limiting the maximum power consumption. It is useful when using the air-conditioner and other electrical devices simultaneously on a shared electrical circuit. This mode helps you in reducing your electricity bills. Radiant cooling enhances comfort cooling by evenly distributing air in every corner of the room. With the help of one click on your remote control, experience enhanced comfort.',
        mrp: 38100,
        price: 27500,
        gst: 0.18,
        grossVolume: '0.8 TON',
        energyRating: '3 Star',
        swing: '',
        inverter_non_inverter: 'NON INVERTER',
        model: 'FTL30UV',
        imageUrl: '/ac/30-0.8ton-3star/main-img.png',
        thumbnail_images: {
          imageUrl: '/ac/30-0.8ton-3star/main-img.png',
          thumbnail1: '/ac/30-0.8ton-3star/tb-1.png',
          thumbnail2: '/ac/30-0.8ton-3star/tb-2.png',
          thumbnail3: '/ac/30-0.8ton-3star/tb-3.png',
        },
      },
    ],
  },
  {
    id: 'ventilation',
    category: 'ventilation',
    name: 'Ventilation',
    products: [
      {
        id: 1,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'ACCELERO DX',
        description:
          '150 mm ACCELERO DX VENTIL AIR FAN, Easy Installation High Quality Engineering plastic with dynamic aesthetics Blades designed for strong air suction to keep the air clean and fres',
        mrp: 1860,
        price: 1575,
        power: '22W',
        speed: 1350,
        swing: '150mm',
        model: 'DX',
        imageUrl: '/ventilation/v-1/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-1/main-img.png',
          thumbnail1: '/ventilation/v-1/tb-1.png',
          thumbnail2: '/ventilation/v-1/tb-2.png',
          thumbnail3: '/ventilation/v-1/tb-3.png',
        },
      },
      {
        id: 2,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'ACCELERO DX',
        description:
          '200 mm ACCELERO DX VENTIL AIR FAN, Easy Installation High Quality Engineering plastic with dynamic aesthetics Blades designed for strong air suction to keep the air clean and fres',
        mrp: 2050,
        price: 1740,
        power: '31W',
        speed: 1325,
        swing: '200mm',
        model: 'DX',
        imageUrl: '/ventilation/v-2/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-2/main-img.png',
          thumbnail1: '/ventilation/v-2/tb-1.png',
          thumbnail2: '/ventilation/v-2/tb-2.png',
          thumbnail3: '/ventilation/v-2/tb-3.png',
        },
      },
      {
        id: 3,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'ACCELERO DX',
        description:
          '250 mm ACCELERO DX VENTIL AIR FAN, Easy Installation High Quality Engineering plastic with dynamic aesthetics  Blades designed for strong air suction to keep the air clean and fres',
        mrp: 2180,
        price: 1845,
        power: '36W',
        speed: 1250,
        swing: '250mm',
        model: 'DX',
        imageUrl: '/ventilation/v-3/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-3/main-img.png',
          thumbnail1: '/ventilation/v-3/tb-1.png',
          thumbnail2: '/ventilation/v-3/tb-2.png',
          thumbnail3: '/ventilation/v-3/tb-3.png',
        },
      },
      {
        id: 4,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'VENTILAIR DB',
        description:
          '230 mm FAN VENTIL AIR DB, Double ball bearings Protective steel bird guard Robust construction',
        mrp: 3150,
        price: 2670,
        power: '45W',
        speed: 1400,
        swing: '230mm',
        model: 'DB',
        imageUrl: '/ventilation/v-4/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-4/main-img.png',
          thumbnail1: '/ventilation/v-4/tb-1.png',
          thumbnail2: '/ventilation/v-4/tb-2.png',
        },
      },
      {
        id: 5,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'VENTILAIR DB',
        description:
          '300 mm FAN VENTIL AIR DB, Double ball bearings Protective steel bird guard Robust construction',
        mrp: 3820,
        price: 3235,
        power: '70W',
        speed: 1400,
        swing: '300mm',
        model: 'DB',
        imageUrl: '/ventilation/v-5/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-5/main-img.png',
          thumbnail1: '/ventilation/v-5/tb-1.png',
          thumbnail2: '/ventilation/v-5/tb-2.png',
        },
      },
      {
        id: 6,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'VENTILAIR DSP',
        description:
          '230 mm FAN VENTIL AIR DSP ,Specially designed metal blade Powder coated long lasting finish Rust free bird guard Special coating for easy cleaning grease & dust',
        mrp: 2180,
        price: 1845,
        power: '40W',
        speed: 1350,
        swing: '230mm',
        model: 'DSP',
        imageUrl: '/ventilation/v-6/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-6/main-img.png',
          thumbnail1: '/ventilation/v-6/tb-1.png',
          thumbnail2: '/ventilation/v-6/tb-2.png',
        },
      },
      {
        id: 7,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'VENTILAIR DSP',
        description:
          '300 mm FAN VENTIL AIR DX, Double ball bearings Heavy duty motor for longer life Metal blades and body for better strength Protective bird guard',
        mrp: 2720,
        price: 2305,
        power: '50W',
        speed: 1350,
        swing: '300mm',
        model: 'DSP',
        imageUrl: '/ventilation/v-7/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-7/main-img.png',
          thumbnail1: '/ventilation/v-7/tb-1.png',
          thumbnail2: '/ventilation/v-7/tb-2.png',
        },
      },
      {
        id: 8,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'TURBO FORCE NEO',
        description: 'TURBOFORCE - NEO 450 mm/1400 rpm -1P, Corrosion resistant body, minimal noise operation & maintenance free design  Totally enclosed, highly efficient heavy duty motor with pressure die cast aluminium rotor mounted on two ball bearings   Aerodynamically contoured blades handle maximum air with minimum power consumption.  Rigid frame with rubber mountings for silent operation Conforming to IS: 2312 -1967 Available in various sizes with I & III phase An IP55 rated product (protected from limited dust ingress and from low pressure water jets from any direction',
        mrp: 9060,
        price: 7680,
        power: '410W',
        speed: 1400,
        swing: '450mm',
        model: 'FORCE NEO',
        imageUrl: '/ventilation/v-8/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-8/main-img.png',
          thumbnail1: '/ventilation/v-8/tb-1.png',
        },
      },
      {
        id: 9,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'HAVELLS',
        productTitle: 'TURBO FORCE NEO',
        description:
          'TURBOFORCE - NEO 600 mm/900 rpm -1P,  Corrosion resistant body, minimal noise operation & maintenance free design  Totally enclosed, highly efficient heavy duty motor with pressure die cast aluminium rotor mounted on two ball bearings   Aerodynamically contoured blades handle maximum air with minimum power consumption.  Rigid frame with rubber mountings for silent operation Conforming to IS: 2312 -1967 Available in various sizes with I & III phase An IP55 rated product (protected from limited dust ingress and from low pressure water jets from any direction',
        mrp: 17660,
        price: 14970,
        power: '500W',
        speed: 900,
        swing: '600mm',
        model: 'FORCE NEO',
        imageUrl: '/ventilation/v-9/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-9/main-img.png',
          thumbnail1: '/ventilation/v-9/tb-1.png',
        },
      },
      {
        id: 10,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'TUULI Metallic Exhaust Fans',
        description:
          'TUULI Metallic VENTIL AIR FAN,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and fre',
        mrp: 1920,
        price: 1632,
        power: '49W',
        speed: 2650,
        swing: '150mm',
        model: 'LME60',
        imageUrl: '/ventilation/v-10/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-10/main-img.png',
        },
      },
      {
        id: 11,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'TUULI Metallic Exhaust Fans',
        description:
          'TUULI Metallic VENTIL AIR FAN,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and fre',
        mrp: 2080,
        price: 1768,
        power: '40W',
        speed: 1400,
        swing: '225mm',
        model: 'LME60',
        imageUrl: '/ventilation/v-11/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-11/main-img.png',
        },
      },
      {
        id: 12,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'TUULI Metallic Exhaust Fans',
        description:
          'TUULI Metallic VENTIL AIR FAN,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 2140,
        price: 1819,
        power: '60W',
        speed: 2400,
        swing: '230mm',
        model: 'LME09HS',
        imageUrl: '/ventilation/v-12/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-12/main-img.png',
        },
      },
      {
        id: 13,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'TUULI Metallic Exhaust Fans',
        description:
          'TUULI Metallic VENTIL AIR FAN,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 2440,
        price: 2074,
        power: '52W',
        speed: 1400,
        swing: '300mm',
        model: 'LME12',
        imageUrl: '/ventilation/v-13/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-13/main-img.png',
        },
      },
      {
        id: 14,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'CIELO Ceiling Exhaust Fans (LXCEL8i)',
        description:
          'CIELO Ceiling Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 2780,
        price: 2363,
        power: '250W',
        speed: 1400,
        swing: '200mm',
        model: 'LXCELC08',
        imageUrl: '/ventilation/v-14/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-14/main-img.png',
          thumbnail1: '/ventilation/v-14/tb-1.png',
          thumbnail2: '/ventilation/v-14/tb-2.png',
          thumbnail3: '/ventilation/v-14/tb-3.png',
        },
      },
      {
        id: 15,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'CIELO Ceiling Exhaust Fans(LXCEL12)',
        description:
          'CIELO Ceiling Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 2380,
        price: 2788,
        power: '36W',
        speed: 1350,
        swing: '300mm',
        model: 'LXCEL12',
        imageUrl: '/ventilation/v-15/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-15/main-img.png',
          thumbnail1: '/ventilation/v-15/tb-1.png',
          thumbnail2: '/ventilation/v-15/tb-2.png',
        },
      },
      {
        id: 16,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'CIELO Ceiling Exhaust Fans',
        description:
          'CIELO Ceiling Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 3080,
        price: 2618,
        power: '31W',
        speed: 1350,
        swing: '200mm',
        model: 'LXCEL&8I RW',
        imageUrl: '/ventilation/v-15/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-16/main-img.png',
          thumbnail1: '/ventilation/v-16/tb-1.png',
          thumbnail2: '/ventilation/v-16/tb-2.png',
        },
      },
      {
        id: 17,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'CIELO NEO Ceiling Exhaust Fans',
        description:
          'CIELO Ceiling Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 2780,
        price: 2363,
        power: '21W',
        speed: 1350,
        swing: '200mm',
        model: 'LXCEL&I 8L',
        imageUrl: '/ventilation/v-17/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-17/main-img.png',
          thumbnail1: '/ventilation/v-17/tb-1.png',
        },
      },
      {
        id: 18,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'GALE PLUS AX-R Exhaust Fans',
        description:
          'GALE PLUS AX-R Exhaust Fans, Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1070,
        price: 909,
        power: '21W',
        speed: 2100,
        swing: '150mm',
        model: 'GALE PLUS AX-R ',
        imageUrl: '/ventilation/v-18/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-18/main-img.png',
        },
      },
      {
        id: 19,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'CIEGO AX-R Exhaust Fans',
        description:
          'CIEGO AX-R Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 2650,
        price: 2252,
        power: '20W',
        speed: 1900,
        swing: '150mm',
        model: 'CIEGO',
        imageUrl: '/ventilation/v-19/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-19/main-img.png',
          thumbnail1: '/ventilation/v-19/tb-1.png',
        },
      },
      {
        id: 20,
        category: 'ventilation',
        subCategory: 'Exhaust Fans',
        brand: 'LUKER',
        productTitle: 'ESEN AX-R Exhaust Fans',
        description:
          'ESEN AX-R Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1280,
        price: 1088,
        power: '21W',
        speed: 2100,
        swing: '150mm',
        model: 'ESEN AX-R',
        imageUrl: '/ventilation/v-20/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-20/main-img.png',
        },
      },
      {
        id: 21,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'LUKER',
        productTitle: 'ESEN AX-R Exhaust Fans',
        description:
          'ESEN AX-R Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1280,
        price: 1088,
        power: '21W',
        speed: 2100,
        swing: '150mm',
        model: 'ESEN AX-R',
        imageUrl: '/ventilation/v-21/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-21/main-img.png',
        },
      },
      {
        id: 22,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'LUKER',
        productTitle: 'ESEN AX-R Exhaust Fans',
        description:
          'ESEN AX-R Exhaust Fans,    Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1680,
        price: 1428,
        power: '24W',
        speed: 2000,
        swing: '200mm',
        model: 'ESEN AX-R',
        imageUrl: '/ventilation/v-22/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-22/main-img.png',
        },
      },
      {
        id: 23,
        category: 'ventilation',
        subCategory: 'Cabinet Fans',
        brand: 'LUKER',
        productTitle: 'VIENTO HS Exhaust Fans',
        description:
          'VIENTO HS Exhaust Fans,Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1680,
        price: 1428,
        power: '43W',
        speed: 2500,
        swing: '150mm',
        model: 'VIENTO HS',
        imageUrl: '/ventilation/v-23/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-23/main-img.png',
          thumbnail1: '/ventilation/v-23/tb-1.png',
          thumbnail2: '/ventilation/v-23/tb-2.png',
        },
      },
      {
        id: 24,
        category: 'ventilation',
        subCategory: 'Cabinet Fans',
        brand: 'LUKER',
        productTitle: 'VIENTO HS Exhaust Fans',
        description:
          'VIENTO HS Exhaust Fans,Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and fre',
        mrp: 1940,
        price: 1649,
        power: '70W',
        speed: 1750,
        swing: '200mm',
        model: 'VIENTO HS',
        imageUrl: '/ventilation/v-24/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-24/main-img.png',
          thumbnail1: '/ventilation/v-24/tb-1.png',
          thumbnail2: '/ventilation/v-24/tb-2.png',
        },
      },
      {
        id: 25,
        category: 'ventilation',
        subCategory: 'Cabinet Fans',
        brand: 'LUKER',
        productTitle: 'VIENTO Exhaust Fans',
        description:
          'VIENTO Exhaust Fans,Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1560,
        price: 1326,
        power: '30W',
        speed: 1400,
        swing: '150mm',
        model: 'VIENTO',
        imageUrl: '/ventilation/v-25/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-25/main-img.png',
          thumbnail1: '/ventilation/v-25/tb-1.png',
          thumbnail2: '/ventilation/v-25/tb-2.png',
        },
      },
      {
        id: 26,
        category: 'ventilation',
        subCategory: 'Cabinet Fans',
        brand: 'LUKER',
        productTitle: 'VIENTO Exhaust Fans',
        description:
          'VIENTO Exhaust Fans,Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1760,
        price: 1496,
        power: '35W',
        speed: 1350,
        swing: '200mm',
        model: 'VIENTO',
        imageUrl: '/ventilation/v-26/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-26/main-img.png',
          thumbnail1: '/ventilation/v-26/tb-1.png',
          thumbnail2: '/ventilation/v-26/tb-2.png',
        },
      },
      {
        id: 27,
        category: 'ventilation',
        subCategory: 'Cabinet Fans',
        brand: 'LUKER',
        productTitle: 'VIENTO Exhaust Fans',
        description:
          'VIENTO Exhaust Fans,Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1980,
        price: 1683,
        power: '38W',
        speed: 1250,
        swing: '250mm',
        model: 'VIENTO',
        imageUrl: '/ventilation/v-27/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-27/main-img.png',
          thumbnail1: '/ventilation/v-27/tb-1.png',
          thumbnail2: '/ventilation/v-27/tb-2.png',
        },
      },
      {
        id: 28,
        category: 'ventilation',
        subCategory: 'Cabinet Fans',
        brand: 'LUKER',
        productTitle: 'VENTIL AIR -LXB SERIES',
        description:
          'VENTIL AIR -LXB SERIES, Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 1590,
        price: 1352,
        power: '12W',
        speed: 2100,
        swing: '100mm',
        model: 'XB SERIES',
        imageUrl: '/ventilation/v-27/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-27/main-img.png',
          thumbnail1: '/ventilation/v-27/tb-1.png',
          thumbnail2: '/ventilation/v-27/tb-2.png',
        },
      },
      {
        id: 29,
        category: 'ventilation',
        subCategory: 'Cabinet Fans',
        brand: 'LUKER',
        productTitle: 'VENTIL AIR -LXB SERIES',
        description:
          'VENTIL AIR -LXB SERIES, Easy Installation High Quality Engineering plastic with dynamic aesthetics,  Blades designed for strong air suction to keep the air clean and free',
        mrp: 2590,
        price: 2201,
        power: '24W',
        speed: 2300,
        swing: '150mm',
        model: 'LXB SERIES',
        imageUrl: '/ventilation/v-27/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-27/main-img.png',
          thumbnail1: '/ventilation/v-27/tb-1.png',
          thumbnail2: '/ventilation/v-27/tb-2.png',
        },
      },
      {
        id: 30,
        category: 'ventilation',
        subCategory: 'Inline Fans',
        brand: 'CROMPTON',
        productTitle: 'TRANSAIR/TRANSAIR REVERSIBLE',
        description:
          'WITH THE FLICK OF A SWITCH OE CAN OPT EXHAUST MODE OR FRESH AIR MODE IN TRANSAIR REVERSIBLE,METAL BIRD SCREEN FOR PROCTECTION FROM BIRDS AND FOREIGN MATTER',
        mrp: 2999,
        price: 2549,
        power: '50W',
        speed: 2000,
        swing: '150mm',
        model: 'TRANSAIR/TRANSAIR REVERSIBLE',
        imageUrl: '/ventilation/v-30/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-30/main-img.png',
          thumbnail1: '/ventilation/v-30/tb-1.png',
          thumbnail2: '/ventilation/v-30/tb-2.png',
          thumbnail3: '/ventilation/v-30/tb-3.png',
        },
      },
      {
        id: 31,
        category: 'ventilation',
        subCategory: 'Inline Fans',
        brand: 'CROMPTON',
        productTitle: 'TRANSAIR/TRANSAIR REVERSIBLE',
        description:
          'WITH THE FLICK OF A SWITCH OE CAN OPT EXHAUST MODE OR FRESH AIR MODE IN TRANSAIR REVERSIBLE,METAL BIRD SCREEN FOR PROCTECTION FROM BIRDS AND FOREIGN MATTER',
        mrp: 3249,
        price: 2761,
        power: '45W',
        speed: 1400,
        swing: '225mm',
        model: 'TRANSAIR/TRANSAIR REVERSIBLE',
        imageUrl: '/ventilation/v-31/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-31/main-img.png',
          thumbnail1: '/ventilation/v-31/tb-1.png',
          thumbnail2: '/ventilation/v-31/tb-2.png',
          thumbnail3: '/ventilation/v-31/tb-3.png',
        },
      },
      {
        id: 32,
        category: 'ventilation',
        subCategory: 'Inline Fans',
        brand: 'CROMPTON',
        productTitle: 'TRANSAIR/TRANSAIR REVERSIBLE',
        description:
          'WITH THE FLICK OF A SWITCH OE CAN OPT EXHAUST MODE OR FRESH AIR MODE IN TRANSAIR REVERSIBLE,METAL BIRD SCREEN FOR PROCTECTION FROM BIRDS AND FOREIGN MATTER',
        mrp: 3399,
        price: 2889,
        power: '70W',
        speed: 1380,
        swing: '300mm',
        model: 'TRANSAIR/TRANSAIR REVERSIBLE',
        imageUrl: '/ventilation/v-32/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-32/main-img.png',
          thumbnail1: '/ventilation/v-32/tb-1.png',
          thumbnail2: '/ventilation/v-32/tb-2.png',
          thumbnail3: '/ventilation/v-32/tb-3.png',
        },
      },
      {
        id: 33,
        category: 'ventilation',
        subCategory: 'Inline Fans',
        brand: 'CROMPTON',
        productTitle: 'DRIFT AIR PLUS',
        description:
          'STUDY METAL BODY WITH METAL BLADES, METAL BIRD SCREEN FOR PROTECTION FROM BIRDS AND FOREIGN MATTER, NEW VARIANT AVAILABLE WITH ANTI- DUST COATING',
        mrp: 1999,
        price: 1699,
        power: '42W',
        speed: 2300,
        swing: '150mm',
        model: 'DRIFT AIR PLUS',
        imageUrl: '/ventilation/v-33/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-33/main-img.png',
          thumbnail1: '/ventilation/v-33/tb-1.png',
          thumbnail2: '/ventilation/v-33/tb-2.png',
        },
      },
      {
        id: 34,
        category: 'ventilation',
        subCategory: 'Inline Fans',
        brand: 'CROMPTON',
        productTitle: 'DRIFT AIR PLUS',
        description:
          'STUDY METAL BODY WITH METAL BLADES, METAL BIRD SCREEN FOR PROTECTION FROM BIRDS AND FOREIGN MATTER, NEW VARIANT AVAILABLE WITH ANTI- DUST COATING',
        mrp: 2099,
        price: 1784,
        power: '35W',
        speed: 1370,
        swing: '225mm',
        model: 'DRIFT AIR PLUS',
        imageUrl: '/ventilation/v-34/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-34/main-img.png',
          thumbnail1: '/ventilation/v-34/tb-1.png',
          thumbnail2: '/ventilation/v-34/tb-2.png',
        },
      },
      {
        id: 35,
        category: 'ventilation',
        subCategory: 'Ventilation Kit',
        brand: 'CROMPTON',
        productTitle: 'DRIFT AIR PLUS',
        description:
          'STUDY METAL BODY WITH METAL BLADES, METAL BIRD SCREEN FOR PROTECTION FROM BIRDS AND FOREIGN MATTER, NEW VARIANT AVAILABLE WITH ANTI- DUST COATING',
        mrp: 2099,
        price: 1784,
        power: '48W',
        speed: 1370,
        swing: '300mm',
        model: 'DRIFT AIR PLUS',
        imageUrl: '/ventilation/v-35/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-35/main-img.png',
          thumbnail1: '/ventilation/v-35/tb-1.png',
          thumbnail2: '/ventilation/v-35/tb-2.png',
        },
      },
      {
        id: 36,
        category: 'ventilation',
        subCategory: 'Ventilation Kit',
        brand: 'CROMPTON',
        productTitle: 'FLUX AIR',
        description:
          'STUDY METAL BODY WITH METAL BLADE IT COMES WITH CORROSION RESISTANT COATING ON BLADE & BOADY',
        mrp: 1899,
        price: 1615,
        power: '31W',
        speed: 1380,
        swing: '225mm',
        model: 'FLUX AIR',
        imageUrl: '/ventilation/v-36/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-36/main-img.png',
          thumbnail1: '/ventilation/v-36/tb-1.png',
          thumbnail2: '/ventilation/v-36/tb-2.png',
          thumbnail3: '/ventilation/v-36/tb-3.png',
        },
      },
      {
        id: 37,
        category: 'ventilation',
        subCategory: 'Ventilation Kit',
        brand: 'CROMPTON',
        productTitle: 'NEW MOUNT AIR',
        description:
          'Light weight and sleek design with abs body, silent operation and superior air flow, can be installed on glass,wall and ceiling',
        mrp: 1649,
        price: 1402,
        power: '11W',
        speed: 2500,
        swing: '100mm',
        model: 'NEW MOUNT AIR',
        imageUrl: '/ventilation/v-37/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-37/main-img.png',
          thumbnail1: '/ventilation/v-37/tb-1.png',
          thumbnail2: '/ventilation/v-37/tb-2.png',
          thumbnail3: '/ventilation/v-37/tb-3.png',
        },
      },
      {
        id: 38,
        category: 'ventilation',
        subCategory: 'Ventilation Kit',
        brand: 'CROMPTON',
        productTitle: 'NEW MOUNT AIR',
        description:
          'light weight and sleek design with abs body, silent operation and superior air flow, can be installed on glass,wall and ceiling',
        mrp: 2349,
        price: 1996,
        power: '20W',
        speed: 1500,
        swing: '150mm',
        model: 'NEW MOUNT AIR',
        imageUrl: '/ventilation/v-38/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-38/main-img.png',
          thumbnail1: '/ventilation/v-38/tb-1.png',
          thumbnail2: '/ventilation/v-38/tb-2.png',
          thumbnail3: '/ventilation/v-38/tb-3.png',
        },
      },
      {
        id: 39,
        category: 'ventilation',
        subCategory: 'Ventilation Kit',
        brand: 'CROMPTON',
        productTitle: 'AXIAL AIR',
        description:
          'STURDY front grill for additional safety',
        mrp: 1499,
        price: 1274,
        power: '12W',
        speed: 2400,
        swing: '100mm',
        model: 'AXIAL AIR',
        imageUrl: '/ventilation/v-39/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-39/main-img.png',
          thumbnail1: '/ventilation/v-39/tb-1.png',
          thumbnail2: '/ventilation/v-39/tb-2.png',
          thumbnail3: '/ventilation/v-39/tb-3.png',
        },
      },
      {
        id: 40,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'AXIAL AIR',
        description:
          'STURDY front grill for additional safety, ',
        mrp: 1499,
        price: 1274,
        power: '20W',
        speed: 1750,
        swing: '150mm',
        model: 'AXIAL AIR',
        imageUrl: '/ventilation/v-40/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-40/main-img.png',
          thumbnail1: '/ventilation/v-40/tb-1.png',
          thumbnail2: '/ventilation/v-40/tb-2.png',
          thumbnail3: '/ventilation/v-40/tb-3.png',
        },
      },
      {
        id: 41,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'AXIAL AIR',
        description:
          'STURDY front grill for additional safety',
        mrp: 1499,
        price: 1274,
        power: '33W',
        speed: 1585,
        swing: '200mm',
        model: 'AXIAL AIR',
        imageUrl: '/ventilation/v-41/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-41/main-img.png',
          thumbnail1: '/ventilation/v-41/tb-1.png',
          thumbnail2: '/ventilation/v-41/tb-2.png',
          thumbnail3: '/ventilation/v-41/tb-3.png',
        },
      },
      {
        id: 42,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'BRISK AIR NEO',
        description:
          'sleek design with aerodynamic blades, black flaps for prevention of entry of dust and foreign particles',
        mrp: 1999,
        price: 1699,
        power: '25W',
        speed: 1350,
        swing: '150mm',
        model: 'BRISK AIR NEO',
        imageUrl: '/ventilation/v-42/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-42/main-img.png',
          thumbnail1: '/ventilation/v-42/tb-1.png',
          thumbnail2: '/ventilation/v-42/tb-2.png',
          thumbnail3: '/ventilation/v-42/tb-3.png',
        },
      },
      {
        id: 43,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'BRISK AIR NEO',
        description:
          'sleek design with aerodynamic blades, black flaps for prevention of entry of dust and foreign particles',
        mrp: 2149,
        price: 1826,
        power: '27W',
        speed: 1350,
        swing: '200mm',
        model: 'BRISK AIR NEO',
        imageUrl: '/ventilation/v-43/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-43/main-img.png',
          thumbnail1: '/ventilation/v-43/tb-1.png',
          thumbnail2: '/ventilation/v-43/tb-2.png',
          thumbnail3: '/ventilation/v-43/tb-3.png',
        },
      },
      {
        id: 44,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'BRISK AIR NEO',
        description:
          'sleek design with aerodynamic blades, black flaps for prevention of entry of dust and foreign particles',
        mrp: 2349,
        price: 1996,
        power: '27W',
        speed: 1310,
        swing: '250mm',
        model: 'BRISK AIR NEO',
        imageUrl: '/ventilation/v-44/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-44/main-img.png',
          thumbnail1: '/ventilation/v-44/tb-1.png',
          thumbnail2: '/ventilation/v-44/tb-2.png',
          thumbnail3: '/ventilation/v-44/tb-3.png',
        },
      },
      {
        id: 45,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'BRISK AIR PLUS',
        description:
          'sleek design with aerodynamic blades, black flaps for prevention of entry of dust and foreign particles',
        mrp: 1999,
        price: 1996,
        power: '25W',
        speed: 1300,
        swing: '150mm',
        model: 'BRISK AIR PLUS',
        imageUrl: '/ventilation/v-45/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-45/main-img.png',
          thumbnail1: '/ventilation/v-45/tb-1.png',
          thumbnail2: '/ventilation/v-45/tb-2.png',
          thumbnail3: '/ventilation/v-45/tb-3.png',
        },
      },
      {
        id: 46,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'BRISK AIR PLUS',
        description:
          'sleek design with aerodynamic blades, black flaps for prevention of entry of dust and foreign particles',
        mrp: 2099,
        price: 1784,
        power: '30W',
        speed: 1300,
        swing: '200mm',
        model: 'BRISK AIR PLUS',
        imageUrl: '/ventilation/v-46/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-46/main-img.png',
          thumbnail1: '/ventilation/v-46/tb-1.png',
          thumbnail2: '/ventilation/v-46/tb-2.png',
          thumbnail3: '/ventilation/v-46/tb-3.png',
        },
      },
      {
        id: 47,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'BRISK AIR PLUS',
        description:
          'sleek design with aerodynamic blades, black flaps for prevention of entry of dust and foreign particles',
        mrp: 2349,
        price: 1996,
        power: '35W',
        speed: 1300,
        swing: '250mm',
        model: 'BRISK AIR PLUS',
        imageUrl: '/ventilation/v-47/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-47/main-img.png',
          thumbnail1: '/ventilation/v-47/tb-1.png',
          thumbnail2: '/ventilation/v-47/tb-2.png',
          thumbnail3: '/ventilation/v-47/tb-3.png',
        },
      },
      {
        id: 48,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'BRISK AIR CM',
        description:
          'Modern Aesthetics, automatic louvers',
        mrp: 2349,
        price: 1996,
        power: '28W',
        speed: 1400,
        swing: '110mm',
        model: 'BRISK AIR CM',
        imageUrl: '/ventilation/v-48/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-48/main-img.png',
          thumbnail1: '/ventilation/v-48/tb-1.png',
          thumbnail2: '/ventilation/v-48/tb-2.png',
        },
      },
      {
        id: 49,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'VENTILUS',
        description:
          'Automatic shutter for dust protection, also available in lvory',
        mrp: 1999,
        price: 1699,
        power: '25W',
        speed: 1300,
        swing: '150mm',
        model: 'VENTILUS',
        imageUrl: '/ventilation/v-49/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-49/main-img.png',
          thumbnail1: '/ventilation/v-49/tb-1.png',
          thumbnail2: '/ventilation/v-49/tb-2.png',
        },
      },
      {
        id: 50,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'VENTILUS',
        description:
          'Automatic shutter for dust protection, also available in lvory',
        mrp: 2099,
        price: 1784,
        power: '30W',
        speed: 1300,
        swing: '200mm',
        model: 'VENTILUS',
        imageUrl: '/ventilation/v-50/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-50/main-img.png',
          thumbnail1: '/ventilation/v-50/tb-1.png',
          thumbnail2: '/ventilation/v-50/tb-2.png',
        },
      },
      {
        id: 51,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'VENTILUS',
        description:
          'Automatic shutter for dust protection, also available in lvory',
        mrp: 2349,
        price: 1996,
        power: '35W',
        speed: 1300,
        swing: '250mm',
        model: 'VENTILUS',
        imageUrl: '/ventilation/v-51/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-51/main-img.png',
          thumbnail1: '/ventilation/v-51/tb-1.png',
          thumbnail2: '/ventilation/v-51/tb-2.png',
        },
      },
      {
        id: 52,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'VENTILUS HS',
        description:
          'High speed operation, Automatic shutter for dust protection',
        mrp: 2099,
        price: 1784,
        power: '33W',
        speed: 2400,
        swing: '150mm',
        model: 'VENTILUS HS',
        imageUrl: '/ventilation/v-52/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-52/main-img.png',
          thumbnail1: '/ventilation/v-52/tb-1.png',
          thumbnail2: '/ventilation/v-52/tb-2.png',
          thumbnail3: '/ventilation/v-52/tb-3.png',
        },
      },
      {
        id: 53,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'VENTILUS HS',
        description:
          'High speed operation, Automatic shutter for dust protection',
        mrp: 2349,
        price: 1996,
        power: '38W',
        speed: 1800,
        swing: '200mm',
        model: 'VENTILUS HS',
        imageUrl: '/ventilation/v-53/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-53/main-img.png',
          thumbnail1: '/ventilation/v-53/tb-1.png',
          thumbnail2: '/ventilation/v-53/tb-2.png',
          thumbnail3: '/ventilation/v-53/tb-3.png',
        },
      },
      {
        id: 54,
        category: 'ventilation',
        subCategory: 'Fresh Air Fans',
        brand: 'CROMPTON',
        productTitle: 'HEAVY DUTY EXHAUST FANS',
        description:
          'TOTALLY ENCLOSED,CONTINOUSLY RATED HIGHLY EFFICIENT HEAVY -DUTY MOTOR, AERODYNAMICALLY CONTOURE BLADES PROVIDE MAXIMUM AIR WITH MINIMUM POWER CONSUMPTION',
        mrp: 6249,
        price: 5311,
        power: '',
        speed: '',
        swing: '',
        model: 'HEAVY DUTY ',
        imageUrl: '/ventilation/v-54/main-img.png',
        thumbnail_images: {
          imageUrl: '/ventilation/v-54/main-img.png',
          thumbnail1: '/ventilation/v-54/tb-1.png',
          thumbnail2: '/ventilation/v-54/tb-2.png',
        },
      },
    ],
  },
];
